# This is the default error serializer generated by Lucky.
# Feel free to customize it in any way you like.
class ErrorSerializer < BaseSerializer
  def initialize(
    @message : String,
    @details : String? = nil,
    @param : String? = nil # so you can track which param (if any) caused the problem
  )
  end

  def render
    case {@details.nil?, @param.nil?}
    when {false, false}
      {message: @message, param: @param, details: @details}
    when {false, true}
      {message: @message, details: @details}
    when {true, false}
      {message: @message, param: @param}
    when {true, true}
      {message: @message}
    end
  end
end
